/-
Copyright (c) 2024-2025 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao, Katerina Hristova, František Silváši, Julian Sutherland,
         Ilia Vlasov, Chung Thai Nguyen
-/

import ArkLib.Data.CodingTheory.ProximityGap.BCIKS20.ErrorBound

namespace ProximityGap

namespace WeightedAgreement

open NNReal Finset Function ProbabilityTheory
open scoped BigOperators Pointwise ProbabilityTheory
open ReedSolomonCode Uniform

section ProbabilityTheorems

variable {ι : Type} [Fintype ι] [Nonempty ι]
variable {F : Type} [Field F] [Fintype F] [DecidableEq F]

instance {domain : ι ↪ F} {deg : ℕ} : Nonempty (finCarrier domain deg) := by
  rcases Submodule.nonempty (ReedSolomon.code domain deg) with ⟨v, hv⟩
  refine ⟨v, ?_⟩
  simpa [ReedSolomonCode.finCarrier, Set.mem_toFinset] using hv

/-- Weighted correlated agreement over curves.
Take a Reed-Solomon code of length `ι` and degree `deg`, a proximity-error parameter
pair `(δ, ε)` and a curve generated by vectors `u`, such that the probability that a random
point on the curve is `δ`-close to Reed-Solomon code is at most `ε`.
Then, the words `u` have weighted correlated agreement. -/
theorem weighted_correlated_agreement_for_parameterized_curves [DecidableEq ι]
    {l : ℕ} {k : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F} {δ : ℝ≥0}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {M : ℕ}
    {α : ℝ≥0}
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ)) :
    letI sqrtRate := ReedSolomonCode.sqrtRate deg domain
    (hα : sqrtRate < α) →
    (hα₁ : α < 1) →
    letI ε := ProximityGap.errorBound δ deg domain
    letI pr :=
      let curvePts := Curve.polynomialCurveFinite (F := F) (A := F) u
      Pr_{let y ←$ᵖ curvePts}[agree_set μ y (finCarrier domain deg) ≥ α]
    (hproximity : pr > (l + 1 : NNReal) * ε) →
    (h_additionally : pr ≥
      ENNReal.ofReal (
        ((l + 1) * (M * Fintype.card ι + 1) : ℝ) / (Fintype.card F : ℝ)
        *
        (1 / min (α - sqrtRate) (sqrtRate / 20) + 3 / sqrtRate)
      )
    ) →
    ∃ ι' : Finset ι, ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ ι' ≥ α ∧
      ∀ i, ∀ x ∈ ι', u i x = v i x := by
  sorry

/-- Weighted correlated agreement over curves.
Take a Reed-Solomon code of length `ι` and degree `deg`, a proximity-error parameter
pair `(δ, ε)` and a curve generated by vectors `u`, such that the probability that a random
point on the curve is `δ`-close to Reed-Solomon code is at most `ε`.
Then, the words `u` have weighted correlated agreement.

Version with different bounds. -/
theorem weighted_correlated_agreement_for_parameterized_curves' [DecidableEq ι]
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F} {δ : ℝ≥0}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {M m : ℕ}
    (hm : 3 ≤ m)
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ))
    {α : ℝ≥0} :
    letI sqrtRate := ReedSolomonCode.sqrtRate deg domain
    letI S : Finset F := {
      z : F |
        agree_set μ (Curve.polynomialCurveEval (F := F) (A := F) u z) (finCarrier domain deg) ≥ α
    }
    (hα : sqrtRate * (1 + 1 / (2 * m : ℝ)) ≤ α) →
    (hS :
      Finset.card S >
        max ((1 + 1 / (2 * m : ℝ)) ^ 7 * m ^ 7 * (Fintype.card ι) ^ 2 * (l + 1) /
            (3 * sqrtRate ^ 3))
          ((2 * m + 1) * (M * Fintype.card ι + 1) * (l + 1) / sqrtRate.toReal)
    ) →
    ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ { i : ι | ∀ j, u j i = v j i } ≥ α := by
  sorry

/-- Weighted correlated agreement over affine spaces.
Take a Reed-Solomon code of length `ι` and degree `deg`, a proximity-error parameter
pair `(δ, ε)` and an affine space generated by vectors `u`, such that the probability that a random
point from the space is `δ`-close to Reed-Solomon code is at most `ε`.
Then, the words `u` have weighted correlated agreement. -/
theorem weighted_correlated_agreement_over_affine_spaces
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {M : ℕ}
    {α : ℝ≥0} :
    letI sqrtRate := ReedSolomonCode.sqrtRate deg domain
    (hα : sqrtRate < α) →
    (hα₁ : α < 1) →
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ)) →
    letI ε := ProximityGap.errorBound α deg domain
    letI pr :=
      let spacePts :=
        u 0 +ᵥ affineSpan F (((Finset.univ.image (Fin.tail u) : Finset (ι → F)) : Set (ι → F)))
      Pr_{let y ←$ᵖ spacePts}[agree_set μ y (finCarrier domain deg) ≥ α]
    pr > ε →
    pr ≥ ENNReal.ofReal (
      ((M * Fintype.card ι + 1) : ℝ) / (Fintype.card F : ℝ)
      *
      (1 / min (α - sqrtRate) (sqrtRate / 20) + 3 / sqrtRate)
    ) →
    ∃ ι' : Finset ι, ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ ι' ≥ α ∧
      ∀ i, ∀ x ∈ ι', u i x = v i x := by
  sorry

/-- Weighted correlated agreement over affine spaces.
Take a Reed-Solomon code of length `ι` and degree `deg`, a proximity-error parameter
pair `(δ, ε)` and an affine space generated by vectors `u`, such that the probability that a random
point from the space is `δ`-close to Reed-Solomon code is at most `ε`.
Then, the words `u` have weighted correlated agreement.

Version with different bounds. -/
theorem weighted_correlated_agreement_over_affine_spaces'
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {α : ℝ≥0}
    {M m : ℕ}
    (hm : 3 ≤ m)
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ)) :
    letI sqrtRate := ReedSolomonCode.sqrtRate deg domain
    letI pr :=
      let spacePts :=
        u 0 +ᵥ affineSpan F (((Finset.univ.image (Fin.tail u) : Finset (ι → F)) : Set (ι → F)))
      Pr_{let y ←$ᵖ spacePts}[agree_set μ y (finCarrier domain deg) ≥ α]
    (hα : sqrtRate * (1 + 1 / (2 * m : ℝ)) ≤ α) →
    letI numeratorl : ℝ := (1 + 1 / (2 * m : ℝ)) ^ 7 * m ^ 7 * (Fintype.card ι) ^ 2
    letI denominatorl : ℝ := (3 * sqrtRate ^ 3) * Fintype.card F
    letI numeratorr : ℝ := (2 * m + 1) * (M * Fintype.card ι + 1)
    letI denominatorr : ℝ := sqrtRate * Fintype.card F
    pr > ENNReal.ofReal (max (numeratorl / denominatorl) (numeratorr / denominatorr)) →
    ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ { i : ι | ∀ j, u j i = v j i } ≥ α := by
  sorry

end ProbabilityTheorems

section ListAgreementLemmas

variable {ι : Type} [Fintype ι] [Nonempty ι]
variable {F : Type} [Field F] [Fintype F] [DecidableEq F]

/--
Lemma 7.5 in [BCIKS20].

This is the "list agreement on a curve implies correlated agreement" lemma.

We are given two lists of functions `u, v : Fin (l + 2) → ι → F`, where each `v i` is a
Reed-Solomon codeword of degree `deg` over the evaluation domain `domain`. From these
lists we form the bivariate curve evaluations

* `w x z = Curve.polynomialCurveEval u z x`,
* `wtilde x z = Curve.polynomialCurveEval v z x`.

Fix a finite set `S' ⊆ F` with `S'.card > l + 1`, and a (product) measure `μ` on the
evaluation domain `ι`. Assume that for every `z ∈ S'` the one-dimensional functions
`w · z` and `wtilde · z` have agreement at least `α` with respect to `μ`. Then the set
of points `x` on which all coordinates agree, i.e. `u i x = v i x` for every `i`,
has μ-measure strictly larger than

`α - (l + 1) / (S'.card - (l + 1))`. -/
lemma list_agreement_on_curve_implies_correlated_agreement_bound
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {α : ℝ≥0}
    {v : Fin (l + 2) → ι → F}
    (hv : ∀ i, v i ∈ ReedSolomon.code domain deg)
    {S' : Finset F}
    (hS'_card : S'.card > l + 1) :
    letI w (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) u z x
    letI wtilde (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) v z x
    (hS'_agree : ∀ z ∈ S', agree μ (w · z) (wtilde · z) ≥ α) →
    mu_set μ { x : ι | ∀ i, u i x = v i x } >
      α - ((l + 1) : ℝ) / (S'.card - (l + 1)) := by
  sorry

/--
Lemma 7.6 in [BCIKS20].

This is the "integral-weight" strengthening of the list-agreement-on-a-curve =>
correlated-agreement bound.

We have two lists of functions `u, v : Fin (l + 2) → ι → F`, where each `v i` is a
Reed-Solomon codeword of degree `deg` over the evaluation domain `domain`. From
these lists we form the bivariate curve evaluations

* `w x z = Curve.polynomialCurveEval u z x`,
* `wtilde x z = Curve.polynomialCurveEval v z x`.

The domain `ι` is finite and is equipped with a weighted measure `μ`, where each
weight `μ i` is a rational with common denominator `M`. Let `S' ⊆ F` be a set of
field points with
* `S'.card > l + 1`, and
* `S'.card ≥ (M * Fintype.card ι + 1) * (l + 1)`.

Assume that for every `z ∈ S'` the µ-weighted agreement between `w · z` and
`wtilde · z` is at least `α`. Then the µ-measure of the set of points where all
coordinates agree, i.e. where `u i x = v i x` for every `i`, is at least `α`:

`mu_set μ {x | ∀ i, u i x = v i x} ≥ α`. -/
lemma sufficiently_large_list_agreement_on_curve_implies_correlated_agreement
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {α : ℝ≥0}
    {M : ℕ}
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ))
    {v : Fin (l + 2) → ι → F}
    (hv : ∀ i, v i ∈ ReedSolomon.code domain deg)
    {S' : Finset F}
    (hS'_card : S'.card > l + 1)
    (hS'_card₁ : S'.card ≥ (M * Fintype.card ι + 1) * (l + 1)) :
    letI w (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) u z x
    letI wtilde (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) v z x
    (hS'_agree : ∀ z ∈ S', agree μ (w · z) (wtilde · z) ≥ α) →
    mu_set μ { x : ι | ∀ i, u i x = v i x } ≥ α := by
  sorry

end ListAgreementLemmas

end WeightedAgreement

end ProximityGap
